package com.rtiming.shared.ecard.download;

import java.util.List;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "com.rtiming.client.ecard.download.CourseAndClassFromECardForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class CourseAndClassFromECardFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public Clazz getClazz() {
    return getFieldByClass(Clazz.class);
  }

  /**
   * access method for property Controls.
   */
  public List<PunchFormData> getControls() {
    return getControlsProperty().getValue();
  }

  /**
   * access method for property Controls.
   */
  public void setControls(List<PunchFormData> controls) {
    getControlsProperty().setValue(controls);
  }

  public ControlsProperty getControlsProperty() {
    return getPropertyByClass(ControlsProperty.class);
  }

  public Course getCourse() {
    return getFieldByClass(Course.class);
  }

  public Event getEvent() {
    return getFieldByClass(Event.class);
  }

  public static class Clazz extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class ControlsProperty extends AbstractPropertyData<List<PunchFormData>> {

    private static final long serialVersionUID = 1L;
  }

  public static class Course extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class Event extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }
}
