package com.rtiming.shared.ecard.download;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "com.rtiming.client.ecard.download.ECardStationForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class ECardStationFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public Baud getBaud() {
    return getFieldByClass(Baud.class);
  }

  public ClientAddress getClientAddress() {
    return getFieldByClass(ClientAddress.class);
  }

  /**
   * access method for property ECardStationNr.
   */
  public Long getECardStationNr() {
    return getECardStationNrProperty().getValue();
  }

  /**
   * access method for property ECardStationNr.
   */
  public void setECardStationNr(Long eCardStationNr) {
    getECardStationNrProperty().setValue(eCardStationNr);
  }

  public ECardStationNrProperty getECardStationNrProperty() {
    return getPropertyByClass(ECardStationNrProperty.class);
  }

  public Identifier getIdentifier() {
    return getFieldByClass(Identifier.class);
  }

  public Modus getModus() {
    return getFieldByClass(Modus.class);
  }

  public Port getPort() {
    return getFieldByClass(Port.class);
  }

  public PosPrinter getPosPrinter() {
    return getFieldByClass(PosPrinter.class);
  }

  public Printer getPrinter() {
    return getFieldByClass(Printer.class);
  }

  public static class Baud extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class ClientAddress extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class ECardStationNrProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class Identifier extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class Modus extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class Port extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class PosPrinter extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class Printer extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }
}
