package com.rtiming.shared.event;

import java.util.Date;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "com.rtiming.client.event.EventForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class EventFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  /**
   * access method for property ClientNr.
   */
  public Long getClientNr() {
    return getClientNrProperty().getValue();
  }

  /**
   * access method for property ClientNr.
   */
  public void setClientNr(Long clientNr) {
    getClientNrProperty().setValue(clientNr);
  }

  public ClientNrProperty getClientNrProperty() {
    return getPropertyByClass(ClientNrProperty.class);
  }

  /**
   * access method for property EventNr.
   */
  public Long getEventNr() {
    return getEventNrProperty().getValue();
  }

  /**
   * access method for property EventNr.
   */
  public void setEventNr(Long eventNr) {
    getEventNrProperty().setValue(eventNr);
  }

  public EventNrProperty getEventNrProperty() {
    return getPropertyByClass(EventNrProperty.class);
  }

  public EventType getEventType() {
    return getFieldByClass(EventType.class);
  }

  /**
   * access method for property EvtLastUpload.
   */
  public Date getEvtLastUpload() {
    return getEvtLastUploadProperty().getValue();
  }

  /**
   * access method for property EvtLastUpload.
   */
  public void setEvtLastUpload(Date evtLastUpload) {
    getEvtLastUploadProperty().setValue(evtLastUpload);
  }

  public EvtLastUploadProperty getEvtLastUploadProperty() {
    return getPropertyByClass(EvtLastUploadProperty.class);
  }

  public FinishTime getFinishTime() {
    return getFieldByClass(FinishTime.class);
  }

  /**
   * access method for property Format.
   */
  public String getFormat() {
    return getFormatProperty().getValue();
  }

  /**
   * access method for property Format.
   */
  public void setFormat(String format) {
    getFormatProperty().setValue(format);
  }

  public FormatProperty getFormatProperty() {
    return getPropertyByClass(FormatProperty.class);
  }

  public Location getLocation() {
    return getFieldByClass(Location.class);
  }

  /**
   * access method for property LogoData.
   */
  public byte[] getLogoData() {
    return getLogoDataProperty().getValue();
  }

  /**
   * access method for property LogoData.
   */
  public void setLogoData(byte[] logoData) {
    getLogoDataProperty().setValue(logoData);
  }

  public LogoDataProperty getLogoDataProperty() {
    return getPropertyByClass(LogoDataProperty.class);
  }

  public Mapp getMapp() {
    return getFieldByClass(Mapp.class);
  }

  public Name getName() {
    return getFieldByClass(Name.class);
  }

  public PunchingSystem getPunchingSystem() {
    return getFieldByClass(PunchingSystem.class);
  }

  public Timezone getTimezone() {
    return getFieldByClass(Timezone.class);
  }

  public ZeroTime getZeroTime() {
    return getFieldByClass(ZeroTime.class);
  }

  public static class ClientNrProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class EventNrProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class EventType extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class EvtLastUploadProperty extends AbstractPropertyData<Date> {

    private static final long serialVersionUID = 1L;
  }

  public static class FinishTime extends AbstractValueFieldData<Date> {

    private static final long serialVersionUID = 1L;
  }

  public static class FormatProperty extends AbstractPropertyData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class Location extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class LogoDataProperty extends AbstractPropertyData<byte[]> {

    private static final long serialVersionUID = 1L;
  }

  public static class Mapp extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class Name extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class PunchingSystem extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class Timezone extends AbstractValueFieldData<Integer> {

    private static final long serialVersionUID = 1L;
  }

  public static class ZeroTime extends AbstractValueFieldData<Date> {

    private static final long serialVersionUID = 1L;
  }
}
