package com.rtiming.shared.runner;

import java.util.Date;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.fields.AbstractFormFieldData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "com.rtiming.client.runner.AbstractRunnerDetailsSearchBox", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public abstract class AbstractRunnerDetailsSearchBoxData extends AbstractFormFieldData {

  private static final long serialVersionUID = 1L;

  public BirthdateFrom getBirthdateFrom() {
    return getFieldByClass(BirthdateFrom.class);
  }

  public BirthdateTo getBirthdateTo() {
    return getFieldByClass(BirthdateTo.class);
  }

  public DefaultClazz getDefaultClazz() {
    return getFieldByClass(DefaultClazz.class);
  }

  public NationUid getNationUid() {
    return getFieldByClass(NationUid.class);
  }

  public Sex getSex() {
    return getFieldByClass(Sex.class);
  }

  public YearFrom getYearFrom() {
    return getFieldByClass(YearFrom.class);
  }

  public YearTo getYearTo() {
    return getFieldByClass(YearTo.class);
  }

  public static class BirthdateFrom extends AbstractValueFieldData<Date> {

    private static final long serialVersionUID = 1L;
  }

  public static class BirthdateTo extends AbstractValueFieldData<Date> {

    private static final long serialVersionUID = 1L;
  }

  public static class DefaultClazz extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class NationUid extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class Sex extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class YearFrom extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class YearTo extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }
}
