package com.rtiming.shared.runner;

import java.util.Date;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

import com.rtiming.shared.settings.addinfo.AbstractAdditionalInformationFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "com.rtiming.client.runner.RunnerForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class RunnerFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public AbstractAddressBoxData getAbstractAddressBoxData() {
    return getFieldByClass(AbstractAddressBoxData.class);
  }

  public Active getActive() {
    return getFieldByClass(Active.class);
  }

  public AdditionalInformation getAdditionalInformation() {
    return getFieldByClass(AdditionalInformation.class);
  }

  /**
   * access method for property AddressNr.
   */
  public Long getAddressNr() {
    return getAddressNrProperty().getValue();
  }

  /**
   * access method for property AddressNr.
   */
  public void setAddressNr(Long addressNr) {
    getAddressNrProperty().setValue(addressNr);
  }

  public AddressNrProperty getAddressNrProperty() {
    return getPropertyByClass(AddressNrProperty.class);
  }

  public Birthdate getBirthdate() {
    return getFieldByClass(Birthdate.class);
  }

  /**
   * access method for property ClientNr.
   */
  public Long getClientNr() {
    return getClientNrProperty().getValue();
  }

  /**
   * access method for property ClientNr.
   */
  public void setClientNr(Long clientNr) {
    getClientNrProperty().setValue(clientNr);
  }

  public ClientNrProperty getClientNrProperty() {
    return getPropertyByClass(ClientNrProperty.class);
  }

  public Club getClub() {
    return getFieldByClass(Club.class);
  }

  public DefaultClazz getDefaultClazz() {
    return getFieldByClass(DefaultClazz.class);
  }

  public ECard getECard() {
    return getFieldByClass(ECard.class);
  }

  public ExtKey getExtKey() {
    return getFieldByClass(ExtKey.class);
  }

  public FirstName getFirstName() {
    return getFieldByClass(FirstName.class);
  }

  public LastName getLastName() {
    return getFieldByClass(LastName.class);
  }

  public NationUid getNationUid() {
    return getFieldByClass(NationUid.class);
  }

  /**
   * access method for property RunnerNr.
   */
  public Long getRunnerNr() {
    return getRunnerNrProperty().getValue();
  }

  /**
   * access method for property RunnerNr.
   */
  public void setRunnerNr(Long runnerNr) {
    getRunnerNrProperty().setValue(runnerNr);
  }

  public RunnerNrProperty getRunnerNrProperty() {
    return getPropertyByClass(RunnerNrProperty.class);
  }

  public Sex getSex() {
    return getFieldByClass(Sex.class);
  }

  public Year getYear() {
    return getFieldByClass(Year.class);
  }

  public static class AbstractAddressBoxData extends com.rtiming.shared.settings.city.AbstractAddressBoxData {

    private static final long serialVersionUID = 1L;
  }

  public static class Active extends AbstractValueFieldData<Boolean> {

    private static final long serialVersionUID = 1L;
  }

  public static class AdditionalInformation extends AbstractAdditionalInformationFieldData {

    private static final long serialVersionUID = 1L;

    @Override
    public AdditionalInformationRowData addRow() {
      return (AdditionalInformationRowData) super.addRow();
    }

    @Override
    public AdditionalInformationRowData addRow(int rowState) {
      return (AdditionalInformationRowData) super.addRow(rowState);
    }

    @Override
    public AdditionalInformationRowData createRow() {
      return new AdditionalInformationRowData();
    }

    @Override
    public Class<? extends AbstractTableRowData> getRowType() {
      return AdditionalInformationRowData.class;
    }

    @Override
    public AdditionalInformationRowData[] getRows() {
      return (AdditionalInformationRowData[]) super.getRows();
    }

    @Override
    public AdditionalInformationRowData rowAt(int index) {
      return (AdditionalInformationRowData) super.rowAt(index);
    }

    public void setRows(AdditionalInformationRowData[] rows) {
      super.setRows(rows);
    }

    public static class AdditionalInformationRowData extends AbstractAdditionalInformationRowData {

      private static final long serialVersionUID = 1L;
    }
  }

  public static class AddressNrProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class Birthdate extends AbstractValueFieldData<Date> {

    private static final long serialVersionUID = 1L;
  }

  public static class ClientNrProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class Club extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class DefaultClazz extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class ECard extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class ExtKey extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class FirstName extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class LastName extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class NationUid extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class RunnerNrProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class Sex extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class Year extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }
}
