package com.rtiming.shared.event.course;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "com.rtiming.client.event.course.ControlsSearchForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class ControlsSearchFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public ActiveGroup getActiveGroup() {
    return getFieldByClass(ActiveGroup.class);
  }

  public static class ActiveGroup extends AbstractValueFieldData<Boolean> {

    private static final long serialVersionUID = 1L;
  }
}
