package com.rtiming.shared.settings.account;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "com.rtiming.client.settings.account.AccountForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class AccountFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public AccountInfo getAccountInfo() {
    return getFieldByClass(AccountInfo.class);
  }

  /**
   * access method for property AccountNr.
   */
  public Long getAccountNr() {
    return getAccountNrProperty().getValue();
  }

  /**
   * access method for property AccountNr.
   */
  public void setAccountNr(Long accountNr) {
    getAccountNrProperty().setValue(accountNr);
  }

  public AccountNrProperty getAccountNrProperty() {
    return getPropertyByClass(AccountNrProperty.class);
  }

  /**
   * access method for property ClientNr.
   */
  public Long getClientNr() {
    return getClientNrProperty().getValue();
  }

  /**
   * access method for property ClientNr.
   */
  public void setClientNr(Long clientNr) {
    getClientNrProperty().setValue(clientNr);
  }

  public ClientNrProperty getClientNrProperty() {
    return getPropertyByClass(ClientNrProperty.class);
  }

  public EMail getEMail() {
    return getFieldByClass(EMail.class);
  }

  public FirstName getFirstName() {
    return getFieldByClass(FirstName.class);
  }

  public LastName getLastName() {
    return getFieldByClass(LastName.class);
  }

  public NameInfo getNameInfo() {
    return getFieldByClass(NameInfo.class);
  }

  public Password getPassword() {
    return getFieldByClass(Password.class);
  }

  public PasswordInfo getPasswordInfo() {
    return getFieldByClass(PasswordInfo.class);
  }

  public RepeatPassword getRepeatPassword() {
    return getFieldByClass(RepeatPassword.class);
  }

  /**
   * access method for property UpdatePassword.
   */
  public boolean isUpdatePassword() {
    return getUpdatePasswordProperty().getValue() == null ? false : getUpdatePasswordProperty().getValue();
  }

  /**
   * access method for property UpdatePassword.
   */
  public void setUpdatePassword(boolean updatePassword) {
    getUpdatePasswordProperty().setValue(updatePassword);
  }

  public UpdatePasswordProperty getUpdatePasswordProperty() {
    return getPropertyByClass(UpdatePasswordProperty.class);
  }

  public Username getUsername() {
    return getFieldByClass(Username.class);
  }

  public static class AccountInfo extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class AccountNrProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class ClientNrProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class EMail extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class FirstName extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class LastName extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class NameInfo extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class Password extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class PasswordInfo extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class RepeatPassword extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class UpdatePasswordProperty extends AbstractPropertyData<Boolean> {

    private static final long serialVersionUID = 1L;
  }

  public static class Username extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }
}
