package com.rtiming.shared.entry;

import java.util.Date;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "com.rtiming.client.entry.RegistrationForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class RegistrationFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public EvtRegistration getEvtRegistration() {
    return getFieldByClass(EvtRegistration.class);
  }

  public RegistrationNo getRegistrationNo() {
    return getFieldByClass(RegistrationNo.class);
  }

  /**
   * access method for property RegistrationNr.
   */
  public Long getRegistrationNr() {
    return getRegistrationNrProperty().getValue();
  }

  /**
   * access method for property RegistrationNr.
   */
  public void setRegistrationNr(Long registrationNr) {
    getRegistrationNrProperty().setValue(registrationNr);
  }

  public RegistrationNrProperty getRegistrationNrProperty() {
    return getPropertyByClass(RegistrationNrProperty.class);
  }

  public StartlistSettingOptionGroupBox getStartlistSettingOptionGroupBox() {
    return getFieldByClass(StartlistSettingOptionGroupBox.class);
  }

  public static class EvtRegistration extends AbstractValueFieldData<Date> {

    private static final long serialVersionUID = 1L;
  }

  public static class RegistrationNo extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class RegistrationNrProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class StartlistSettingOptionGroupBox extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }
}
