package com.rtiming.shared.settings.city;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.fields.AbstractFormFieldData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "com.rtiming.client.runner.AbstractAddressBox", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public abstract class AbstractAddressBoxData extends AbstractFormFieldData {

  private static final long serialVersionUID = 1L;

  public City getCity() {
    return getFieldByClass(City.class);
  }

  public EMail getEMail() {
    return getFieldByClass(EMail.class);
  }

  public Fax getFax() {
    return getFieldByClass(Fax.class);
  }

  public Mobile getMobile() {
    return getFieldByClass(Mobile.class);
  }

  public Phone getPhone() {
    return getFieldByClass(Phone.class);
  }

  public Street getStreet() {
    return getFieldByClass(Street.class);
  }

  public Url getUrl() {
    return getFieldByClass(Url.class);
  }

  public static class City extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class EMail extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class Fax extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class Mobile extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class Phone extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class Street extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class Url extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }
}
