package com.rtiming.shared.settings.city;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.fields.AbstractFormFieldData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "com.rtiming.client.settings.city.AbstractCitySearchBox", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public abstract class AbstractCitySearchBoxData extends AbstractFormFieldData {

  private static final long serialVersionUID = 1L;

  public Area getArea() {
    return getFieldByClass(Area.class);
  }

  public City getCity() {
    return getFieldByClass(City.class);
  }

  public Country getCountry() {
    return getFieldByClass(Country.class);
  }

  public Region getRegion() {
    return getFieldByClass(Region.class);
  }

  public Zip getZip() {
    return getFieldByClass(Zip.class);
  }

  public static class Area extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class City extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class Country extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class Region extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class Zip extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }
}
