package com.rtiming.shared.ranking;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.fields.AbstractFormFieldData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "com.rtiming.client.ranking.AbstractRankingBox", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public abstract class AbstractRankingBoxData extends AbstractFormFieldData {

  private static final long serialVersionUID = 1L;

  public DecimalPlaces getDecimalPlaces() {
    return getFieldByClass(DecimalPlaces.class);
  }

  public Format getFormat() {
    return getFieldByClass(Format.class);
  }

  public Formula getFormula() {
    return getFieldByClass(Formula.class);
  }

  public FormulaType getFormulaType() {
    return getFieldByClass(FormulaType.class);
  }

  public Sorting getSorting() {
    return getFieldByClass(Sorting.class);
  }

  public TimePrecision getTimePrecision() {
    return getFieldByClass(TimePrecision.class);
  }

  public static class DecimalPlaces extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class Format extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class Formula extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class FormulaType extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class Sorting extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class TimePrecision extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }
}
