package com.rtiming.shared.ranking;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

import com.rtiming.shared.dao.RtRankingEventKey;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "com.rtiming.client.ranking.RankingEventForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class RankingEventFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public Event getEvent() {
    return getFieldByClass(Event.class);
  }

  /**
   * access method for property Key.
   */
  public RtRankingEventKey getKey() {
    return getKeyProperty().getValue();
  }

  /**
   * access method for property Key.
   */
  public void setKey(RtRankingEventKey key) {
    getKeyProperty().setValue(key);
  }

  public KeyProperty getKeyProperty() {
    return getPropertyByClass(KeyProperty.class);
  }

  public RankingBox getRankingBox() {
    return getFieldByClass(RankingBox.class);
  }

  public SortCode getSortCode() {
    return getFieldByClass(SortCode.class);
  }

  public static class Event extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class KeyProperty extends AbstractPropertyData<RtRankingEventKey> {

    private static final long serialVersionUID = 1L;
  }

  public static class RankingBox extends AbstractRankingBoxData {

    private static final long serialVersionUID = 1L;
  }

  public static class SortCode extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }
}
