package com.rtiming.shared.settings.addinfo;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.form.fields.tablefield.AbstractTableFieldBeanData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "com.rtiming.client.settings.addinfo.AbstractAdditionalInformationField", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public abstract class AbstractAdditionalInformationFieldData extends AbstractTableFieldBeanData {

  private static final long serialVersionUID = 1L;

  @Override
  public AbstractAdditionalInformationRowData addRow() {
    return (AbstractAdditionalInformationRowData) super.addRow();
  }

  @Override
  public AbstractAdditionalInformationRowData addRow(int rowState) {
    return (AbstractAdditionalInformationRowData) super.addRow(rowState);
  }

  @Override
  public abstract AbstractAdditionalInformationRowData createRow();

  @Override
  public Class<? extends AbstractTableRowData> getRowType() {
    return AbstractAdditionalInformationRowData.class;
  }

  @Override
  public AbstractAdditionalInformationRowData[] getRows() {
    return (AbstractAdditionalInformationRowData[]) super.getRows();
  }

  @Override
  public AbstractAdditionalInformationRowData rowAt(int index) {
    return (AbstractAdditionalInformationRowData) super.rowAt(index);
  }

  public void setRows(AbstractAdditionalInformationRowData[] rows) {
    super.setRows(rows);
  }

  public abstract static class AbstractAdditionalInformationRowData extends AbstractTableRowData {

    private static final long serialVersionUID = 1L;
    public static final String additionalInformationUid = "additionalInformationUid";
    public static final String type = "type";
    public static final String value = "value";
    public static final String integer = "integer";
    public static final String decimal = "decimal";
    public static final String text = "text";
    public static final String minimum = "minimum";
    public static final String maximum = "maximum";
    public static final String feeGroup = "feeGroup";
    public static final String defaultValueInteger = "defaultValueInteger";
    public static final String defaultValueDecimal = "defaultValueDecimal";
    public static final String defaultValueText = "defaultValueText";
    public static final String mandatory = "mandatory";
    private Long m_additionalInformationUid;
    private Long m_type;
    private String m_value;
    private Long m_integer;
    private BigDecimal m_decimal;
    private String m_text;
    private BigDecimal m_minimum;
    private BigDecimal m_maximum;
    private Long m_feeGroup;
    private Long m_defaultValueInteger;
    private BigDecimal m_defaultValueDecimal;
    private String m_defaultValueText;
    private Boolean m_mandatory;

    public Long getAdditionalInformationUid() {
      return m_additionalInformationUid;
    }

    public void setAdditionalInformationUid(Long newAdditionalInformationUid) {
      m_additionalInformationUid = newAdditionalInformationUid;
    }

    public Long getType() {
      return m_type;
    }

    public void setType(Long newType) {
      m_type = newType;
    }

    public String getValue() {
      return m_value;
    }

    public void setValue(String newValue) {
      m_value = newValue;
    }

    public Long getInteger() {
      return m_integer;
    }

    public void setInteger(Long newInteger) {
      m_integer = newInteger;
    }

    public BigDecimal getDecimal() {
      return m_decimal;
    }

    public void setDecimal(BigDecimal newDecimal) {
      m_decimal = newDecimal;
    }

    public String getText() {
      return m_text;
    }

    public void setText(String newText) {
      m_text = newText;
    }

    public BigDecimal getMinimum() {
      return m_minimum;
    }

    public void setMinimum(BigDecimal newMinimum) {
      m_minimum = newMinimum;
    }

    public BigDecimal getMaximum() {
      return m_maximum;
    }

    public void setMaximum(BigDecimal newMaximum) {
      m_maximum = newMaximum;
    }

    public Long getFeeGroup() {
      return m_feeGroup;
    }

    public void setFeeGroup(Long newFeeGroup) {
      m_feeGroup = newFeeGroup;
    }

    public Long getDefaultValueInteger() {
      return m_defaultValueInteger;
    }

    public void setDefaultValueInteger(Long newDefaultValueInteger) {
      m_defaultValueInteger = newDefaultValueInteger;
    }

    public BigDecimal getDefaultValueDecimal() {
      return m_defaultValueDecimal;
    }

    public void setDefaultValueDecimal(BigDecimal newDefaultValueDecimal) {
      m_defaultValueDecimal = newDefaultValueDecimal;
    }

    public String getDefaultValueText() {
      return m_defaultValueText;
    }

    public void setDefaultValueText(String newDefaultValueText) {
      m_defaultValueText = newDefaultValueText;
    }

    public Boolean getMandatory() {
      return m_mandatory;
    }

    public void setMandatory(Boolean newMandatory) {
      m_mandatory = newMandatory;
    }
  }
}
