package com.rtiming.shared.entry.startlist;

import java.util.Date;
import java.util.Set;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "com.rtiming.client.entry.startlist.StartlistSettingForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class StartlistSettingFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public BibNoFrom getBibNoFrom() {
    return getFieldByClass(BibNoFrom.class);
  }

  public BibNoOrderUid getBibNoOrderUid() {
    return getFieldByClass(BibNoOrderUid.class);
  }

  /**
   * access method for property EventNr.
   */
  public Long getEventNr() {
    return getEventNrProperty().getValue();
  }

  /**
   * access method for property EventNr.
   */
  public void setEventNr(Long eventNr) {
    getEventNrProperty().setValue(eventNr);
  }

  public EventNrProperty getEventNrProperty() {
    return getPropertyByClass(EventNrProperty.class);
  }

  public FirstStart getFirstStart() {
    return getFieldByClass(FirstStart.class);
  }

  public LastBibNo getLastBibNo() {
    return getFieldByClass(LastBibNo.class);
  }

  public LastStart getLastStart() {
    return getFieldByClass(LastStart.class);
  }

  /**
   * access method for property NewClassUid.
   */
  public Long getNewClassUid() {
    return getNewClassUidProperty().getValue();
  }

  /**
   * access method for property NewClassUid.
   */
  public void setNewClassUid(Long newClassUid) {
    getNewClassUidProperty().setValue(newClassUid);
  }

  public NewClassUidProperty getNewClassUidProperty() {
    return getPropertyByClass(NewClassUidProperty.class);
  }

  public Options getOptions() {
    return getFieldByClass(Options.class);
  }

  /**
   * access method for property ParticipationCount.
   */
  public Long getParticipationCount() {
    return getParticipationCountProperty().getValue();
  }

  /**
   * access method for property ParticipationCount.
   */
  public void setParticipationCount(Long participationCount) {
    getParticipationCountProperty().setValue(participationCount);
  }

  public ParticipationCountProperty getParticipationCountProperty() {
    return getPropertyByClass(ParticipationCountProperty.class);
  }

  public StartInterval getStartInterval() {
    return getFieldByClass(StartInterval.class);
  }

  /**
   * access method for property StartlistSettingNr.
   */
  public Long getStartlistSettingNr() {
    return getStartlistSettingNrProperty().getValue();
  }

  /**
   * access method for property StartlistSettingNr.
   */
  public void setStartlistSettingNr(Long startlistSettingNr) {
    getStartlistSettingNrProperty().setValue(startlistSettingNr);
  }

  public StartlistSettingNrProperty getStartlistSettingNrProperty() {
    return getPropertyByClass(StartlistSettingNrProperty.class);
  }

  public TypeUid getTypeUid() {
    return getFieldByClass(TypeUid.class);
  }

  public VacantAbsolute getVacantAbsolute() {
    return getFieldByClass(VacantAbsolute.class);
  }

  public VacantPercent getVacantPercent() {
    return getFieldByClass(VacantPercent.class);
  }

  public VacantPositionGroup getVacantPositionGroup() {
    return getFieldByClass(VacantPositionGroup.class);
  }

  public static class BibNoFrom extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class BibNoOrderUid extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class EventNrProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class FirstStart extends AbstractValueFieldData<Date> {

    private static final long serialVersionUID = 1L;
  }

  public static class LastBibNo extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class LastStart extends AbstractValueFieldData<Date> {

    private static final long serialVersionUID = 1L;
  }

  public static class NewClassUidProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class Options extends AbstractValueFieldData<Set<Long>> {

    private static final long serialVersionUID = 1L;
  }

  public static class ParticipationCountProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class StartInterval extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class StartlistSettingNrProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class TypeUid extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class VacantAbsolute extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class VacantPercent extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class VacantPositionGroup extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }
}
