package com.rtiming.shared.ecard;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "com.rtiming.client.ecard.ECardsSearchForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class ECardsSearchFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public ECardBox getECardBox() {
    return getFieldByClass(ECardBox.class);
  }

  public static class ECardBox extends AbstractECardSearchBoxData {

    private static final long serialVersionUID = 1L;
  }
}
