//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.09 at 05:12:48 PM MESZ 
//


package com.rtiming.shared.dataexchange.iof203.xml;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "courseName",
    "courseId",
    "eventId",
    "eventRaceId",
    "classIdOrClassShortName",
    "courseVariation",
    "courseSectionList"
})
@XmlRootElement(name = "Course")
public class Course {

    @XmlElement(name = "CourseName", required = true)
    protected String courseName;
    @XmlElement(name = "CourseId")
    protected String courseId;
    @XmlElement(name = "EventId")
    protected EventId eventId;
    @XmlElement(name = "EventRaceId")
    protected EventRaceId eventRaceId;
    @XmlElements({
        @XmlElement(name = "ClassId", type = ClassId.class),
        @XmlElement(name = "ClassShortName", type = ClassShortName.class)
    })
    protected List<Object> classIdOrClassShortName;
    @XmlElement(name = "CourseVariation")
    protected List<CourseVariation> courseVariation;
    @XmlElement(name = "CourseSectionList")
    protected CourseSectionList courseSectionList;

    /**
     * Gets the value of the courseName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * Sets the value of the courseName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseName(String value) {
        this.courseName = value;
    }

    /**
     * Gets the value of the courseId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * Sets the value of the courseId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseId(String value) {
        this.courseId = value;
    }

    /**
     * Gets the value of the eventId property.
     * 
     * @return
     *     possible object is
     *     {@link EventId }
     *     
     */
    public EventId getEventId() {
        return eventId;
    }

    /**
     * Sets the value of the eventId property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventId }
     *     
     */
    public void setEventId(EventId value) {
        this.eventId = value;
    }

    /**
     * Gets the value of the eventRaceId property.
     * 
     * @return
     *     possible object is
     *     {@link EventRaceId }
     *     
     */
    public EventRaceId getEventRaceId() {
        return eventRaceId;
    }

    /**
     * Sets the value of the eventRaceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventRaceId }
     *     
     */
    public void setEventRaceId(EventRaceId value) {
        this.eventRaceId = value;
    }

    /**
     * Gets the value of the classIdOrClassShortName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the classIdOrClassShortName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClassIdOrClassShortName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClassId }
     * {@link ClassShortName }
     * 
     * 
     */
    public List<Object> getClassIdOrClassShortName() {
        if (classIdOrClassShortName == null) {
            classIdOrClassShortName = new ArrayList<Object>();
        }
        return this.classIdOrClassShortName;
    }

    /**
     * Gets the value of the courseVariation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the courseVariation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCourseVariation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CourseVariation }
     * 
     * 
     */
    public List<CourseVariation> getCourseVariation() {
        if (courseVariation == null) {
            courseVariation = new ArrayList<CourseVariation>();
        }
        return this.courseVariation;
    }

    /**
     * Gets the value of the courseSectionList property.
     * 
     * @return
     *     possible object is
     *     {@link CourseSectionList }
     *     
     */
    public CourseSectionList getCourseSectionList() {
        return courseSectionList;
    }

    /**
     * Sets the value of the courseSectionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link CourseSectionList }
     *     
     */
    public void setCourseSectionList(CourseSectionList value) {
        this.courseSectionList = value;
    }

}
