//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.09 at 05:12:48 PM MESZ 
//


package com.rtiming.shared.dataexchange.iof203.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.rtiming.shared.services.dataexchange.iof203 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.rtiming.shared.services.dataexchange.iof203
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EntryDate }
     * 
     */
    public EntryDate createEntryDate() {
        return new EntryDate();
    }

    /**
     * Create an instance of {@link CourseLength }
     * 
     */
    public CourseLength createCourseLength() {
        return new CourseLength();
    }

    /**
     * Create an instance of {@link WebURL }
     * 
     */
    public WebURL createWebURL() {
        return new WebURL();
    }

    /**
     * Create an instance of {@link BadgeList }
     * 
     */
    public BadgeList createBadgeList() {
        return new BadgeList();
    }

    /**
     * Create an instance of {@link EntryFee }
     * 
     */
    public EntryFee createEntryFee() {
        return new EntryFee();
    }

    /**
     * Create an instance of {@link RaceStart }
     * 
     */
    public RaceStart createRaceStart() {
        return new RaceStart();
    }

    /**
     * Create an instance of {@link EntryId }
     * 
     */
    public EntryId createEntryId() {
        return new EntryId();
    }

    /**
     * Create an instance of {@link CourseVariationId }
     * 
     */
    public CourseVariationId createCourseVariationId() {
        return new CourseVariationId();
    }

    /**
     * Create an instance of {@link EventList }
     * 
     */
    public EventList createEventList() {
        return new EventList();
    }

    /**
     * Create an instance of {@link ContactType }
     * 
     */
    public ContactType createContactType() {
        return new ContactType();
    }

    /**
     * Create an instance of {@link FinishId }
     * 
     */
    public FinishId createFinishId() {
        return new FinishId();
    }

    /**
     * Create an instance of {@link FinishPoint }
     * 
     */
    public FinishPoint createFinishPoint() {
        return new FinishPoint();
    }

    /**
     * Create an instance of {@link CourseData }
     * 
     */
    public CourseData createCourseData() {
        return new CourseData();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link Rank }
     * 
     */
    public Rank createRank() {
        return new Rank();
    }

    /**
     * Create an instance of {@link StartMethod }
     * 
     */
    public StartMethod createStartMethod() {
        return new StartMethod();
    }

    /**
     * Create an instance of {@link EntryList }
     * 
     */
    public EntryList createEntryList() {
        return new EntryList();
    }

    /**
     * Create an instance of {@link ClassShortName }
     * 
     */
    public ClassShortName createClassShortName() {
        return new ClassShortName();
    }

    /**
     * Create an instance of {@link LegLength }
     * 
     */
    public LegLength createLegLength() {
        return new LegLength();
    }

    /**
     * Create an instance of {@link MaxNumber }
     * 
     */
    public MaxNumber createMaxNumber() {
        return new MaxNumber();
    }

    /**
     * Create an instance of {@link DistanceFromStart }
     * 
     */
    public DistanceFromStart createDistanceFromStart() {
        return new DistanceFromStart();
    }

    /**
     * Create an instance of {@link ServiceRequest }
     * 
     */
    public ServiceRequest createServiceRequest() {
        return new ServiceRequest();
    }

    /**
     * Create an instance of {@link EventId }
     * 
     */
    public EventId createEventId() {
        return new EventId();
    }

    /**
     * Create an instance of {@link PunchPattern }
     * 
     */
    public PunchPattern createPunchPattern() {
        return new PunchPattern();
    }

    /**
     * Create an instance of {@link ModifyDate }
     * 
     */
    public ModifyDate createModifyDate() {
        return new ModifyDate();
    }

    /**
     * Create an instance of {@link CompetitorList }
     * 
     */
    public CompetitorList createCompetitorList() {
        return new CompetitorList();
    }

    /**
     * Create an instance of {@link BadgeValueId }
     * 
     */
    public BadgeValueId createBadgeValueId() {
        return new BadgeValueId();
    }

    /**
     * Create an instance of {@link Amount }
     * 
     */
    public Amount createAmount() {
        return new Amount();
    }

    /**
     * Create an instance of {@link BadgeLimit }
     * 
     */
    public BadgeLimit createBadgeLimit() {
        return new BadgeLimit();
    }

    /**
     * Create an instance of {@link EventClassification }
     * 
     */
    public EventClassification createEventClassification() {
        return new EventClassification();
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link TeleType }
     * 
     */
    public TeleType createTeleType() {
        return new TeleType();
    }

    /**
     * Create an instance of {@link ClassTypeId }
     * 
     */
    public ClassTypeId createClassTypeId() {
        return new ClassTypeId();
    }

    /**
     * Create an instance of {@link PressList }
     * 
     */
    public PressList createPressList() {
        return new PressList();
    }

    /**
     * Create an instance of {@link Info }
     * 
     */
    public Info createInfo() {
        return new Info();
    }

    /**
     * Create an instance of {@link ClubServiceRequest }
     * 
     */
    public ClubServiceRequest createClubServiceRequest() {
        return new ClubServiceRequest();
    }

    /**
     * Create an instance of {@link Account }
     * 
     */
    public Account createAccount() {
        return new Account();
    }

    /**
     * Create an instance of {@link AllocationMethod }
     * 
     */
    public AllocationMethod createAllocationMethod() {
        return new AllocationMethod();
    }

    /**
     * Create an instance of {@link DeliveredQuantity }
     * 
     */
    public DeliveredQuantity createDeliveredQuantity() {
        return new DeliveredQuantity();
    }

    /**
     * Create an instance of {@link Tele }
     * 
     */
    public Tele createTele() {
        return new Tele();
    }

    /**
     * Create an instance of {@link Date }
     * 
     */
    public Date createDate() {
        return new Date();
    }

    /**
     * Create an instance of {@link Given }
     * 
     */
    public Given createGiven() {
        return new Given();
    }

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link MapTextPosition }
     * 
     */
    public MapTextPosition createMapTextPosition() {
        return new MapTextPosition();
    }

    /**
     * Create an instance of {@link TransactionList }
     * 
     */
    public TransactionList createTransactionList() {
        return new TransactionList();
    }

    /**
     * Create an instance of {@link CourseVariation }
     * 
     */
    public CourseVariation createCourseVariation() {
        return new CourseVariation();
    }

    /**
     * Create an instance of {@link RequestedQuantity }
     * 
     */
    public RequestedQuantity createRequestedQuantity() {
        return new RequestedQuantity();
    }

    /**
     * Create an instance of {@link SubOrganisation }
     * 
     */
    public SubOrganisation createSubOrganisation() {
        return new SubOrganisation();
    }

    /**
     * Create an instance of {@link Point }
     * 
     */
    public Point createPoint() {
        return new Point();
    }

    /**
     * Create an instance of {@link OrganisationId }
     * 
     */
    public OrganisationId createOrganisationId() {
        return new OrganisationId();
    }

    /**
     * Create an instance of {@link EntryFeeId }
     * 
     */
    public EntryFeeId createEntryFeeId() {
        return new EntryFeeId();
    }

    /**
     * Create an instance of {@link CourseBranch }
     * 
     */
    public CourseBranch createCourseBranch() {
        return new CourseBranch();
    }

    /**
     * Create an instance of {@link CourseControl }
     * 
     */
    public CourseControl createCourseControl() {
        return new CourseControl();
    }

    /**
     * Create an instance of {@link PreSelectedClass }
     * 
     */
    public PreSelectedClass createPreSelectedClass() {
        return new PreSelectedClass();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link StartDate }
     * 
     */
    public StartDate createStartDate() {
        return new StartDate();
    }

    /**
     * Create an instance of {@link PunchingUnitType }
     * 
     */
    public PunchingUnitType createPunchingUnitType() {
        return new PunchingUnitType();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link FinishPointCode }
     * 
     */
    public FinishPointCode createFinishPointCode() {
        return new FinishPointCode();
    }

    /**
     * Create an instance of {@link MapPosition }
     * 
     */
    public MapPosition createMapPosition() {
        return new MapPosition();
    }

    /**
     * Create an instance of {@link Box }
     * 
     */
    public Box createBox() {
        return new Box();
    }

    /**
     * Create an instance of {@link SubstituteClass }
     * 
     */
    public SubstituteClass createSubstituteClass() {
        return new SubstituteClass();
    }

    /**
     * Create an instance of {@link DistanceToFinish }
     * 
     */
    public DistanceToFinish createDistanceToFinish() {
        return new DistanceToFinish();
    }

    /**
     * Create an instance of {@link ClassRaceStatus }
     * 
     */
    public ClassRaceStatus createClassRaceStatus() {
        return new ClassRaceStatus();
    }

    /**
     * Create an instance of {@link Control }
     * 
     */
    public Control createControl() {
        return new Control();
    }

    /**
     * Create an instance of {@link ShortName }
     * 
     */
    public ShortName createShortName() {
        return new ShortName();
    }

    /**
     * Create an instance of {@link ServiceOrderNumber }
     * 
     */
    public ServiceOrderNumber createServiceOrderNumber() {
        return new ServiceOrderNumber();
    }

    /**
     * Create an instance of {@link StartList }
     * 
     */
    public StartList createStartList() {
        return new StartList();
    }

    /**
     * Create an instance of {@link EntryClass }
     * 
     */
    public EntryClass createEntryClass() {
        return new EntryClass();
    }

    /**
     * Create an instance of {@link EventClassificationId }
     * 
     */
    public EventClassificationId createEventClassificationId() {
        return new EventClassificationId();
    }

    /**
     * Create an instance of {@link ResultList }
     * 
     */
    public ResultList createResultList() {
        return new ResultList();
    }

    /**
     * Create an instance of {@link AllocationControl }
     * 
     */
    public AllocationControl createAllocationControl() {
        return new AllocationControl();
    }

    /**
     * Create an instance of {@link ForeignAccount }
     * 
     */
    public ForeignAccount createForeignAccount() {
        return new ForeignAccount();
    }

    /**
     * Create an instance of {@link ClassType }
     * 
     */
    public ClassType createClassType() {
        return new ClassType();
    }

    /**
     * Create an instance of {@link ClassId }
     * 
     */
    public ClassId createClassId() {
        return new ClassId();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link PersonResult }
     * 
     */
    public PersonResult createPersonResult() {
        return new PersonResult();
    }

    /**
     * Create an instance of {@link PersonName }
     * 
     */
    public PersonName createPersonName() {
        return new PersonName();
    }

    /**
     * Create an instance of {@link EventRaceId }
     * 
     */
    public EventRaceId createEventRaceId() {
        return new EventRaceId();
    }

    /**
     * Create an instance of {@link IOFVersion }
     * 
     */
    public IOFVersion createIOFVersion() {
        return new IOFVersion();
    }

    /**
     * Create an instance of {@link ValidFromDate }
     * 
     */
    public ValidFromDate createValidFromDate() {
        return new ValidFromDate();
    }

    /**
     * Create an instance of {@link Nationality }
     * 
     */
    public Nationality createNationality() {
        return new Nationality();
    }

    /**
     * Create an instance of {@link EventClass }
     * 
     */
    public EventClass createEventClass() {
        return new EventClass();
    }

    /**
     * Create an instance of {@link Club }
     * 
     */
    public Club createClub() {
        return new Club();
    }

    /**
     * Create an instance of {@link EventOfficial }
     * 
     */
    public EventOfficial createEventOfficial() {
        return new EventOfficial();
    }

    /**
     * Create an instance of {@link ClassResult }
     * 
     */
    public ClassResult createClassResult() {
        return new ClassResult();
    }

    /**
     * Create an instance of {@link ServiceId }
     * 
     */
    public ServiceId createServiceId() {
        return new ServiceId();
    }

    /**
     * Create an instance of {@link Organiser }
     * 
     */
    public Organiser createOrganiser() {
        return new Organiser();
    }

    /**
     * Create an instance of {@link CCardId }
     * 
     */
    public CCardId createCCardId() {
        return new CCardId();
    }

    /**
     * Create an instance of {@link OrganisationServiceRequest }
     * 
     */
    public OrganisationServiceRequest createOrganisationServiceRequest() {
        return new OrganisationServiceRequest();
    }

    /**
     * Create an instance of {@link StartTime }
     * 
     */
    public StartTime createStartTime() {
        return new StartTime();
    }

    /**
     * Create an instance of {@link NotQualifiedSubstituteClass }
     * 
     */
    public NotQualifiedSubstituteClass createNotQualifiedSubstituteClass() {
        return new NotQualifiedSubstituteClass();
    }

    /**
     * Create an instance of {@link Competitor }
     * 
     */
    public Competitor createCompetitor() {
        return new Competitor();
    }

    /**
     * Create an instance of {@link Symbol }
     * 
     */
    public Symbol createSymbol() {
        return new Symbol();
    }

    /**
     * Create an instance of {@link CourseSection }
     * 
     */
    public CourseSection createCourseSection() {
        return new CourseSection();
    }

    /**
     * Create an instance of {@link Press }
     * 
     */
    public Press createPress() {
        return new Press();
    }

    /**
     * Create an instance of {@link PersonList }
     * 
     */
    public PersonList createPersonList() {
        return new PersonList();
    }

    /**
     * Create an instance of {@link TeamSequence }
     * 
     */
    public TeamSequence createTeamSequence() {
        return new TeamSequence();
    }

    /**
     * Create an instance of {@link ClubId }
     * 
     */
    public ClubId createClubId() {
        return new ClubId();
    }

    /**
     * Create an instance of {@link Time }
     * 
     */
    public Time createTime() {
        return new Time();
    }

    /**
     * Create an instance of {@link StartInterval }
     * 
     */
    public StartInterval createStartInterval() {
        return new StartInterval();
    }

    /**
     * Create an instance of {@link AllocationControlType }
     * 
     */
    public AllocationControlType createAllocationControlType() {
        return new AllocationControlType();
    }

    /**
     * Create an instance of {@link RankList }
     * 
     */
    public RankList createRankList() {
        return new RankList();
    }

    /**
     * Create an instance of {@link DividedIntoClass }
     * 
     */
    public DividedIntoClass createDividedIntoClass() {
        return new DividedIntoClass();
    }

    /**
     * Create an instance of {@link BirthDate }
     * 
     */
    public BirthDate createBirthDate() {
        return new BirthDate();
    }

    /**
     * Create an instance of {@link Course }
     * 
     */
    public Course createCourse() {
        return new Course();
    }

    /**
     * Create an instance of {@link Contact }
     * 
     */
    public Contact createContact() {
        return new Contact();
    }

    /**
     * Create an instance of {@link Organisation }
     * 
     */
    public Organisation createOrganisation() {
        return new Organisation();
    }

    /**
     * Create an instance of {@link CourseSectionList }
     * 
     */
    public CourseSectionList createCourseSectionList() {
        return new CourseSectionList();
    }

    /**
     * Create an instance of {@link ClassData }
     * 
     */
    public ClassData createClassData() {
        return new ClassData();
    }

    /**
     * Create an instance of {@link StartPoint }
     * 
     */
    public StartPoint createStartPoint() {
        return new StartPoint();
    }

    /**
     * Create an instance of {@link ClubEntry }
     * 
     */
    public ClubEntry createClubEntry() {
        return new ClubEntry();
    }

    /**
     * Create an instance of {@link Start }
     * 
     */
    public Start createStart() {
        return new Start();
    }

    /**
     * Create an instance of {@link CountryList }
     * 
     */
    public CountryList createCountryList() {
        return new CountryList();
    }

    /**
     * Create an instance of {@link Text }
     * 
     */
    public Text createText() {
        return new Text();
    }

    /**
     * Create an instance of {@link PersonStart }
     * 
     */
    public PersonStart createPersonStart() {
        return new PersonStart();
    }

    /**
     * Create an instance of {@link PunchingUnit }
     * 
     */
    public PunchingUnit createPunchingUnit() {
        return new PunchingUnit();
    }

    /**
     * Create an instance of {@link OrganisationTypeId }
     * 
     */
    public OrganisationTypeId createOrganisationTypeId() {
        return new OrganisationTypeId();
    }

    /**
     * Create an instance of {@link RaceDate }
     * 
     */
    public RaceDate createRaceDate() {
        return new RaceDate();
    }

    /**
     * Create an instance of {@link TeamName }
     * 
     */
    public TeamName createTeamName() {
        return new TeamName();
    }

    /**
     * Create an instance of {@link Transaction }
     * 
     */
    public Transaction createTransaction() {
        return new Transaction();
    }

    /**
     * Create an instance of {@link OrganisationList }
     * 
     */
    public OrganisationList createOrganisationList() {
        return new OrganisationList();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link ClassRaceInfo }
     * 
     */
    public ClassRaceInfo createClassRaceInfo() {
        return new ClassRaceInfo();
    }

    /**
     * Create an instance of {@link Clock }
     * 
     */
    public Clock createClock() {
        return new Clock();
    }

    /**
     * Create an instance of {@link Entry }
     * 
     */
    public Entry createEntry() {
        return new Entry();
    }

    /**
     * Create an instance of {@link TeamStatus }
     * 
     */
    public TeamStatus createTeamStatus() {
        return new TeamStatus();
    }

    /**
     * Create an instance of {@link StartPointCode }
     * 
     */
    public StartPointCode createStartPointCode() {
        return new StartPointCode();
    }

    /**
     * Create an instance of {@link TeamStart }
     * 
     */
    public TeamStart createTeamStart() {
        return new TeamStart();
    }

    /**
     * Create an instance of {@link SplitTime }
     * 
     */
    public SplitTime createSplitTime() {
        return new SplitTime();
    }

    /**
     * Create an instance of {@link ValidToDate }
     * 
     */
    public ValidToDate createValidToDate() {
        return new ValidToDate();
    }

    /**
     * Create an instance of {@link RaceResult }
     * 
     */
    public RaceResult createRaceResult() {
        return new RaceResult();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link FinishDate }
     * 
     */
    public FinishDate createFinishDate() {
        return new FinishDate();
    }

    /**
     * Create an instance of {@link CompetitorStatus }
     * 
     */
    public CompetitorStatus createCompetitorStatus() {
        return new CompetitorStatus();
    }

    /**
     * Create an instance of {@link PersonServiceRequest }
     * 
     */
    public PersonServiceRequest createPersonServiceRequest() {
        return new PersonServiceRequest();
    }

    /**
     * Create an instance of {@link SubOrganisationType }
     * 
     */
    public SubOrganisationType createSubOrganisationType() {
        return new SubOrganisationType();
    }

    /**
     * Create an instance of {@link CourseClimb }
     * 
     */
    public CourseClimb createCourseClimb() {
        return new CourseClimb();
    }

    /**
     * Create an instance of {@link EstimatedLastPrizeTime }
     * 
     */
    public EstimatedLastPrizeTime createEstimatedLastPrizeTime() {
        return new EstimatedLastPrizeTime();
    }

    /**
     * Create an instance of {@link CountryId }
     * 
     */
    public CountryId createCountryId() {
        return new CountryId();
    }

    /**
     * Create an instance of {@link Map }
     * 
     */
    public Map createMap() {
        return new Map();
    }

    /**
     * Create an instance of {@link ControlCode }
     * 
     */
    public ControlCode createControlCode() {
        return new ControlCode();
    }

    /**
     * Create an instance of {@link Class }
     * 
     */
    public Class createClass() {
        return new Class();
    }

    /**
     * Create an instance of {@link ResultSelection }
     * 
     */
    public ResultSelection createResultSelection() {
        return new ResultSelection();
    }

    /**
     * Create an instance of {@link EventRace }
     * 
     */
    public EventRace createEventRace() {
        return new EventRace();
    }

    /**
     * Create an instance of {@link ClassStart }
     * 
     */
    public ClassStart createClassStart() {
        return new ClassStart();
    }

    /**
     * Create an instance of {@link PrizeCeremonyTime }
     * 
     */
    public PrizeCeremonyTime createPrizeCeremonyTime() {
        return new PrizeCeremonyTime();
    }

    /**
     * Create an instance of {@link PersonId }
     * 
     */
    public PersonId createPersonId() {
        return new PersonId();
    }

    /**
     * Create an instance of {@link FinishTime }
     * 
     */
    public FinishTime createFinishTime() {
        return new FinishTime();
    }

    /**
     * Create an instance of {@link EstimatedBestTime }
     * 
     */
    public EstimatedBestTime createEstimatedBestTime() {
        return new EstimatedBestTime();
    }

    /**
     * Create an instance of {@link CCard }
     * 
     */
    public CCard createCCard() {
        return new CCard();
    }

    /**
     * Create an instance of {@link BadgeValue }
     * 
     */
    public BadgeValue createBadgeValue() {
        return new BadgeValue();
    }

    /**
     * Create an instance of {@link FirstStart }
     * 
     */
    public FirstStart createFirstStart() {
        return new FirstStart();
    }

    /**
     * Create an instance of {@link TransferedToClass }
     * 
     */
    public TransferedToClass createTransferedToClass() {
        return new TransferedToClass();
    }

    /**
     * Create an instance of {@link ServiceRequestList }
     * 
     */
    public ServiceRequestList createServiceRequestList() {
        return new ServiceRequestList();
    }

    /**
     * Create an instance of {@link EntryData }
     * 
     */
    public EntryData createEntryData() {
        return new EntryData();
    }

    /**
     * Create an instance of {@link OrganisationType }
     * 
     */
    public OrganisationType createOrganisationType() {
        return new OrganisationType();
    }

    /**
     * Create an instance of {@link ClubList }
     * 
     */
    public ClubList createClubList() {
        return new ClubList();
    }

    /**
     * Create an instance of {@link TeamResult }
     * 
     */
    public TeamResult createTeamResult() {
        return new TeamResult();
    }

    /**
     * Create an instance of {@link ControlPosition }
     * 
     */
    public ControlPosition createControlPosition() {
        return new ControlPosition();
    }

}
