package com.rtiming.shared.club;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;

import com.rtiming.shared.settings.addinfo.AbstractAdditionalInformationSearchBoxData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "com.rtiming.client.club.ClubsSearchForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class ClubsSearchFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public AdditionalInformationBox getAdditionalInformationBox() {
    return getFieldByClass(AdditionalInformationBox.class);
  }

  public ClubBox getClubBox() {
    return getFieldByClass(ClubBox.class);
  }

  public static class AdditionalInformationBox extends AbstractAdditionalInformationSearchBoxData {

    private static final long serialVersionUID = 1L;
  }

  public static class ClubBox extends AbstractClubSearchBoxData {

    private static final long serialVersionUID = 1L;
  }
}
